// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"context"
)

type Querier interface {
	GetAccount(ctx context.Context, code string) (Account, error)
	GetBranch(ctx context.Context, id string) (Branch, error)
	GetEntry(ctx context.Context, id string) (JournalEntry, error)
	GetLastSequence(ctx context.Context, subject string) (int64, error)
	GetPeriod(ctx context.Context, id string) (Period, error)
	// Idempotent: NATS JetStream redelivers on consumer crash after commit but
	// before Ack; a duplicate INSERT would loop forever as Nak'd unique-key
	// violations. Entry.ID is derived from the broker sequence so duplicates
	// collapse to the same row.
	InsertEntry(ctx context.Context, arg InsertEntryParams) error
	// Idempotent for the same reason as InsertEntry.
	InsertLine(ctx context.Context, arg InsertLineParams) error
	ListAccounts(ctx context.Context) ([]Account, error)
	ListBranches(ctx context.Context) ([]Branch, error)
	ListEntries(ctx context.Context) ([]JournalEntry, error)
	ListEntryLines(ctx context.Context, entryID string) ([]JournalLine, error)
	ListLinesForEntries(ctx context.Context, dollar_1 []string) ([]JournalLine, error)
	ListPeriods(ctx context.Context) ([]Period, error)
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
	UpsertBranch(ctx context.Context, arg UpsertBranchParams) error
	UpsertLastSequence(ctx context.Context, arg UpsertLastSequenceParams) error
	UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error
}

var _ Querier = (*Queries)(nil)
