// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccount = `-- name: GetAccount :one
SELECT code, name, type, active
FROM accounts
WHERE code = $1
`

func (q *Queries) GetAccount(ctx context.Context, code string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, code)
	var i Account
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Active,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, name
FROM branches
WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, sequence, subject, entry_date, period_id, currency, description, posted_at
FROM journal_entries
WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.Subject,
		&i.EntryDate,
		&i.PeriodID,
		&i.Currency,
		&i.Description,
		&i.PostedAt,
	)
	return i, err
}

const getLastSequence = `-- name: GetLastSequence :one
SELECT last_sequence FROM subject_offsets WHERE subject = $1
`

func (q *Queries) GetLastSequence(ctx context.Context, subject string) (int64, error) {
	row := q.db.QueryRow(ctx, getLastSequence, subject)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const getPeriod = `-- name: GetPeriod :one
SELECT id, start_at, end_at, status
FROM periods
WHERE id = $1
`

func (q *Queries) GetPeriod(ctx context.Context, id string) (Period, error) {
	row := q.db.QueryRow(ctx, getPeriod, id)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO journal_entries (
    id, sequence, subject, entry_date, period_id, currency, description, posted_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertEntryParams struct {
	ID          string
	Sequence    int64
	Subject     string
	EntryDate   pgtype.Timestamptz
	PeriodID    string
	Currency    string
	Description string
	PostedAt    pgtype.Timestamptz
}

// Idempotent: NATS JetStream redelivers on consumer crash after commit but
// before Ack; a duplicate INSERT would loop forever as Nak'd unique-key
// violations. Entry.ID is derived from the broker sequence so duplicates
// collapse to the same row.
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.Sequence,
		arg.Subject,
		arg.EntryDate,
		arg.PeriodID,
		arg.Currency,
		arg.Description,
		arg.PostedAt,
	)
	return err
}

const insertLine = `-- name: InsertLine :exec
INSERT INTO journal_lines (
    entry_id, line_no, account_code, side, amount, memo, branch_id, tags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (entry_id, line_no) DO NOTHING
`

type InsertLineParams struct {
	EntryID     string
	LineNo      int32
	AccountCode string
	Side        string
	Amount      int64
	Memo        string
	BranchID    string
	Tags        []byte
}

// Idempotent for the same reason as InsertEntry.
func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) error {
	_, err := q.db.Exec(ctx, insertLine,
		arg.EntryID,
		arg.LineNo,
		arg.AccountCode,
		arg.Side,
		arg.Amount,
		arg.Memo,
		arg.BranchID,
		arg.Tags,
	)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT code, name, type, active
FROM accounts
ORDER BY code
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many
SELECT id, name
FROM branches
ORDER BY id
`

func (q *Queries) ListBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, sequence, subject, entry_date, period_id, currency, description, posted_at
FROM journal_entries
ORDER BY sequence
`

func (q *Queries) ListEntries(ctx context.Context) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.Subject,
			&i.EntryDate,
			&i.PeriodID,
			&i.Currency,
			&i.Description,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLines = `-- name: ListEntryLines :many
SELECT entry_id, line_no, account_code, side, amount, memo, branch_id, tags
FROM journal_lines
WHERE entry_id = $1
ORDER BY line_no
`

func (q *Queries) ListEntryLines(ctx context.Context, entryID string) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, listEntryLines, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalLine
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.EntryID,
			&i.LineNo,
			&i.AccountCode,
			&i.Side,
			&i.Amount,
			&i.Memo,
			&i.BranchID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinesForEntries = `-- name: ListLinesForEntries :many
SELECT entry_id, line_no, account_code, side, amount, memo, branch_id, tags
FROM journal_lines
WHERE entry_id = ANY($1::text[])
ORDER BY entry_id, line_no
`

func (q *Queries) ListLinesForEntries(ctx context.Context, dollar_1 []string) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, listLinesForEntries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalLine
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.EntryID,
			&i.LineNo,
			&i.AccountCode,
			&i.Side,
			&i.Amount,
			&i.Memo,
			&i.BranchID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT id, start_at, end_at, status
FROM periods
ORDER BY id
`

func (q *Queries) ListPeriods(ctx context.Context) ([]Period, error) {
	rows, err := q.db.Query(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (code, name, type, active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    type = EXCLUDED.type,
    active = EXCLUDED.active
`

type UpsertAccountParams struct {
	Code   string
	Name   string
	Type   string
	Active bool
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.Exec(ctx, upsertAccount,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Active,
	)
	return err
}

const upsertBranch = `-- name: UpsertBranch :exec
INSERT INTO branches (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
`

type UpsertBranchParams struct {
	ID   string
	Name string
}

func (q *Queries) UpsertBranch(ctx context.Context, arg UpsertBranchParams) error {
	_, err := q.db.Exec(ctx, upsertBranch, arg.ID, arg.Name)
	return err
}

const upsertLastSequence = `-- name: UpsertLastSequence :exec
INSERT INTO subject_offsets (subject, last_sequence)
VALUES ($1, $2)
ON CONFLICT (subject) DO UPDATE
SET last_sequence = GREATEST(subject_offsets.last_sequence, EXCLUDED.last_sequence)
`

type UpsertLastSequenceParams struct {
	Subject      string
	LastSequence int64
}

func (q *Queries) UpsertLastSequence(ctx context.Context, arg UpsertLastSequenceParams) error {
	_, err := q.db.Exec(ctx, upsertLastSequence, arg.Subject, arg.LastSequence)
	return err
}

const upsertPeriod = `-- name: UpsertPeriod :exec
INSERT INTO periods (id, start_at, end_at, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    status = EXCLUDED.status
`

type UpsertPeriodParams struct {
	ID      string
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
	Status  string
}

func (q *Queries) UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error {
	_, err := q.db.Exec(ctx, upsertPeriod,
		arg.ID,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
	)
	return err
}
